export const op01Data = [
    { 
        set: 'OP01', 
        number: '003', 
        color: 'Verde Rojo', 
        name: 'Monkey.D.Luffy (003)', 
        image_url: 'images/op01/003.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454515/one-piece-card-game-romance-dawn-monkeydluffy-003?page=1',
        rarity: 'L',
        cardType: 'Leader',
        cost: '',
        power: '5000',
        subtypes: 'Straw Hat Crew Supernovas',
        attribute: 'Strike',
        artist: '',
        abilities: ['[Activate:Main] [Once Per Turn] (4) (You may rest the specified number of DON!! cards in your cost area): Set up to 1 of your "Supernova" or "Straw Hat Crew" type Character cards with a cost of 5 or less as active. It gains +1000 power during this turn.', 'This card has been officially errata\'d.'],
        marketPrice: '1.08',
        mostRecentSale: '1.51'
    },
    { 
        set: 'OP01', 
        number: '024', 
        color: 'Rojo', 
        name: 'Monkey.D.Luffy (024)', 
        image_url: 'images/op01/024.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/453508/one-piece-card-game-romance-dawn-monkeydluffy-024?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '2',
        power: '3000',
        subtypes: 'Straw Hat Crew Supernovas',
        attribute: 'Strike',
        artist: '',
        abilities: ['[DON!! x2] This Character cannot be K.O.\'d in battle by "Strike" attribute Characters.', '[Activate:Main] [Once Per Turn] Give this Character up to 2 rested DON!! cards.'],
        marketPrice: '1.29',
        mostRecentSale: '0.99'
    },
    { 
        set: 'OP01', 
        number: '029', 
        color: 'Rojo', 
        name: 'Radical Beam!!', 
        image_url: 'images/op01/029.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454550/one-piece-card-game-romance-dawn-radical-beam?page=1',
        rarity: 'UC',
        cardType: 'Event',
        cost: '1',
        power: '',
        subtypes: 'Straw Hat Crew',
        attribute: '',
        artist: '',
        abilities: ['[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 2 or less Life cards, that card gains an additional +2000 power.', 'This card has been officially errata\'d.'],
        marketPrice: '0.41',
        mostRecentSale: '0.30'
    },
    { 
        set: 'OP01', 
        number: '044', 
        color: 'Verde', 
        name: 'Shachi', 
        image_url: 'images/op01/044.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454568/one-piece-card-game-romance-dawn-shachi?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '3',
        power: '4000',
        subtypes: 'Heart Pirates',
        attribute: 'Strike',
        artist: 'Misa Matoki',
        abilities: ['[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)', '[On Play] If you don\'t have [Penguin], play up to 1 [Penguin] from your hand.', 'This card has been officially errata\'d.'],
        marketPrice: '0.07',
        mostRecentSale: '0.08'
    },
    { 
        set: 'OP01', 
        number: '119', 
        color: 'Morado', 
        name: 'Thunder Bagua', 
        image_url: 'images/op01/119.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454663/one-piece-card-game-romance-dawn-thunder-bagua?page=1',
        rarity: 'R',
        cardType: 'Event',
        cost: '2',
        power: '',
        subtypes: 'Animal Kingdom Pirates The Four Emperors',
        attribute: '',
        artist: '',
        abilities: ['[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 2 or less Life cards, add up to 1 DON!! card from your DON!! deck and rest it.', '[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.', 'This card has been officially errata\'d.'],
        marketPrice: '3.87',
        mostRecentSale: '4.99'
    }
];
