export const op01Data = [
    { 
        set: 'OP01', 
        number: '001', 
        color: 'Rojo', 
        name: 'Roronoa Zoro (001)', 
        image_url: 'images/op01/001.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454512/one-piece-card-game-romance-dawn-roronoa-zoro-001?page=1',
        rarity: 'L',
        cardType: 'Leader',
        cost: '',
        power: '5000',
        subtypes: 'Straw Hat Crew Supernovas',
        attribute: 'Slash',
        artist: '',
        abilities: ['[DON!! x1] [Your Turn] All of your Characters gain +1000 power.'],
        marketPrice: '0.85',
        mostRecentSale: '0.79'
    },
    { 
        set: 'OP01', 
        number: '002', 
        color: 'Verde Rojo', 
        name: 'Trafalgar Law (002)', 
        image_url: 'images/op01/002.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/453505/one-piece-card-game-romance-dawn-trafalgar-law-002?page=1',
        rarity: 'L',
        cardType: 'Leader',
        cost: '',
        power: '5000',
        subtypes: 'Heart Pirates Supernovas',
        attribute: 'Slash',
        artist: '',
        abilities: ['[Activate:Main] [Once Per Turn] (2) (You may rest the specified number of DON!! cards in your cost area.): If you have 5 Characters, return 1 of your Characters to your hand. Then, play up to 1 Character with a cost of 5 or less from your hand that is a different color than the returned Character.
This card has been officially errata\'d.'],
        marketPrice: '0.42',
        mostRecentSale: '0.45'
    },
    { 
        set: 'OP01', 
        number: '003', 
        color: 'Verde Rojo', 
        name: 'Monkey.D.Luffy (003)', 
        image_url: 'images/op01/003.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454515/one-piece-card-game-romance-dawn-monkeydluffy-003?page=1',
        rarity: 'L',
        cardType: 'Leader',
        cost: '',
        power: '5000',
        subtypes: 'Straw Hat Crew Supernovas',
        attribute: 'Strike',
        artist: '',
        abilities: ['[Activate:Main] [Once Per Turn] (4) (You may rest the specified number of DON!! cards in your cost area): Set up to 1 of your "Supernova" or "Straw Hat Crew" type Character cards with a cost of 5 or less as active. It gains +1000 power during this turn.', 'This card has been officially errata\'d.'],
        marketPrice: '1.08',
        mostRecentSale: '1.51'
    },
    { 
        set: 'OP01', 
        number: '006', 
        color: 'Rojo', 
        name: 'Otama', 
        image_url: 'images/op01/006.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454518/one-piece-card-game-romance-dawn-otama?page=1',
        rarity: 'UC',
        cardType: 'Character',
        cost: '1',
        power: '0',
        subtypes: 'Land of Wano',
        attribute: 'Special',
        artist: 'Hagane Tsurugi',
        abilities: ['[On Play] Give up to 1 of your opponent\'s Characters -2000 power during this turn.', 'This card has been officially errata\'d.'],
        marketPrice: '0.60',
        mostRecentSale: '0.49'
    },
    { 
        set: 'OP01', 
        number: '007', 
        color: 'Rojo', 
        name: 'Caribou', 
        image_url: 'images/op01/007.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454519/one-piece-card-game-romance-dawn-caribou?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '3',
        power: '4000',
        subtypes: 'Caribou Pirates Supernovas',
        attribute: 'Special',
        artist: 'kankurou',
        abilities: ['[On K.O.] K.O. up to 1 of your opponent\'s Characters with 4000 power or less.', 'This card has been officially errata\'d.'],
        marketPrice: '0.08',
        mostRecentSale: '0.06'
    },
    { 
        set: 'OP01', 
        number: '013', 
        color: 'Rojo', 
        name: 'Sanji', 
        image_url: 'images/op01/013.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454529/one-piece-card-game-romance-dawn-sanji?page=1',
        rarity: 'R',
        cardType: 'Character',
        cost: '2',
        power: '3000',
        subtypes: 'Straw Hat Crew',
        attribute: 'Strike',
        artist: '',
        abilities: ['[Activate:Main] [Once Per Turn] You may add 1 card from your Life area to your hand: This Character gains +2000 power during this turn. Then, give this Character up to 2 rested DON!! cards.'],
        marketPrice: '4.14',
        mostRecentSale: '4.23'
    },
    { 
        set: 'OP01', 
        number: '016', 
        color: 'Rojo', 
        name: 'Nami', 
        image_url: 'images/op01/016.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454534/one-piece-card-game-romance-dawn-nami?page=1',
        rarity: 'R',
        cardType: 'Character',
        cost: '1',
        power: '2000',
        subtypes: 'Straw Hat Crew',
        attribute: 'Special',
        artist: '',
        abilities: ['[On Play] Look at 5 cards from the top of your deck; reveal up to 1 "Straw Hat Crew" type Character card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.', 'This card has been officially errata\'d.'],
        marketPrice: '5.74',
        mostRecentSale: '4.65'
    },
    { 
        set: 'OP01', 
        number: '018', 
        color: 'Rojo', 
        name: 'Hajrudin', 
        image_url: 'images/op01/018.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454540/one-piece-card-game-romance-dawn-hajrudin?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '4',
        power: '6000',
        subtypes: 'Giant New Giant Pirate Crew',
        attribute: 'Strike',
        artist: 'Nekobayashi',
        abilities: [],
        marketPrice: '0.08',
        mostRecentSale: '0.05'
    },
    { 
        set: 'OP01', 
        number: '024', 
        color: 'Rojo', 
        name: 'Monkey.D.Luffy (024)', 
        image_url: 'images/op01/024.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/453508/one-piece-card-game-romance-dawn-monkeydluffy-024?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '2',
        power: '3000',
        subtypes: 'Straw Hat Crew Supernovas',
        attribute: 'Strike',
        artist: '',
        abilities: ['[DON!! x2] This Character cannot be K.O.\'d in battle by "Strike" attribute Characters.', '[Activate:Main] [Once Per Turn] Give this Character up to 2 rested DON!! cards.'],
        marketPrice: '1.29',
        mostRecentSale: '0.99'
    },
    { 
        set: 'OP01', 
        number: '025', 
        color: 'Rojo', 
        name: 'Roronoa Zoro (025)', 
        image_url: 'images/op01/025.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/453510/one-piece-card-game-romance-dawn-roronoa-zoro-025?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '3',
        power: '5000',
        subtypes: 'Straw Hat Crew Supernovas',
        attribute: 'Slash',
        artist: '',
        abilities: ['[Rush] (This card can attack on the turn in which it is played.)'],
        marketPrice: '5.09',
        mostRecentSale: '4.37'
    },
    { 
        set: 'OP01', 
        number: '027', 
        color: 'Rojo', 
        name: 'Round Table', 
        image_url: 'images/op01/027.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454548/one-piece-card-game-romance-dawn-round-table?page=1',
        rarity: 'C',
        cardType: 'Event',
        cost: '4',
        power: '',
        subtypes: 'Beautiful Pirates Supernovas',
        attribute: '',
        artist: '',
        abilities: ['[Main] Give up to 1 of your opponent\'s Characters -10000 power during this turn.', 'This card has been officially errata\'d.'],
        marketPrice: '0.15',
        mostRecentSale: '0.25'
    },
    { 
        set: 'OP01', 
        number: '029', 
        color: 'Rojo', 
        name: 'Radical Beam!!', 
        image_url: 'images/op01/029.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454550/one-piece-card-game-romance-dawn-radical-beam?page=1',
        rarity: 'UC',
        cardType: 'Event',
        cost: '1',
        power: '',
        subtypes: 'Straw Hat Crew',
        attribute: '',
        artist: '',
        abilities: ['[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 2 or less Life cards, that card gains an additional +2000 power.', 'This card has been officially errata\'d.'],
        marketPrice: '0.41',
        mostRecentSale: '0.30'
    },
    { 
        set: 'OP01', 
        number: '030', 
        color: 'Rojo', 
        name: 'In Two Years!! At the Sabaody Archipelago!!', 
        image_url: 'images/op01/030.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/453512/one-piece-card-game-romance-dawn-in-two-years-at-the-sabaody-archipelago?page=1',
        rarity: 'UC',
        cardType: 'Event',
        cost: '1',
        power: '',
        subtypes: 'Straw Hat Crew',
        attribute: '',
        artist: '',
        abilities: ['[Main] Look at 5 cards from the top of your deck; reveal up to 1 "Straw Hat Crew" type Character card and add it to your hand. Then, place the rest at the bottom of your deck in any order.', '[Trigger] Activate this card\'s [Main] effect.', 'This card has been officially errata\'d.'],
        marketPrice: '0.25',
        mostRecentSale: '0.25'
    },
    { 
        set: 'OP01', 
        number: '033', 
        color: 'Verde', 
        name: 'Izo', 
        image_url: 'images/op01/033.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454554/one-piece-card-game-romance-dawn-izo?page=1',
        rarity: 'UC',
        cardType: 'Character',
        cost: '3',
        power: '3000',
        subtypes: 'Former Whitebeard Pirates Land of Wano',
        attribute: 'Ranged',
        artist: '',
        abilities: ['[On Play] Rest up to 1 of your opponent\'s Characters with a cost of 4 or less.', 'This card has been officially errata\'d.'],
        marketPrice: '0.31',
        mostRecentSale: '0.25'
    },
    { 
        set: 'OP01', 
        number: '036', 
        color: 'Verde', 
        name: 'Otsuru', 
        image_url: 'images/op01/036.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454558/one-piece-card-game-romance-dawn-otsuru?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '1',
        power: '3000',
        subtypes: 'Land of Wano',
        attribute: 'Wisdom',
        artist: '',
        abilities: [],
        marketPrice: '0.03',
        mostRecentSale: '0.04'
    },
    { 
        set: 'OP01', 
        number: '037', 
        color: 'Verde', 
        name: 'Kawamatsu', 
        image_url: 'images/op01/037.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454560/one-piece-card-game-romance-dawn-kawamatsu?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '2',
        power: '3000',
        subtypes: 'Fish-Man Land of Wano The Akazaya Nine',
        attribute: 'Slash',
        artist: 'Studio Vigor Co.,Ltd',
        abilities: ['[Trigger] Play this card.'],
        marketPrice: '0.07',
        mostRecentSale: '0.08'
    },
    { 
        set: 'OP01', 
        number: '038', 
        color: 'Verde', 
        name: 'Kanjuro', 
        image_url: 'images/op01/038.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454562/one-piece-card-game-romance-dawn-kanjuro?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '2',
        power: '3000',
        subtypes: 'Land of Wano The Akazaya Nine',
        attribute: 'Slash',
        artist: '',
        abilities: ['[DON!! x1] [When Attacking] K.O. up to 1 of your opponent\'s rested Characters with a cost of 2 or less.', '[On K.O.] Your opponent chooses 1 card from your hand; trash that card.', 'This card has been officially errata\'d.'],
        marketPrice: '0.04',
        mostRecentSale: '0.04'
    },
    { 
        set: 'OP01', 
        number: '040', 
        color: 'Verde', 
        name: 'Kin\'emon', 
        image_url: 'images/op01/040.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/453514/one-piece-card-game-romance-dawn-kinemon?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '6',
        power: '6000',
        subtypes: 'Land of Wano The Akazaya Nine',
        attribute: 'Slash',
        artist: '',
        abilities: ['[On Play] If your Leader is [Kouzuki Oden], play up to 1 "The Akazaya Nine" type Character card with a cost of 3 or less from your hand.', '[DON!! x1] [When Attacking] [Once Per Turn] Set up to 1 of your "The Akazaya Nine" type Character cards with a cost of 3 or less as active.', 'This card has been officially errata\'d.'],
        marketPrice: '0.47',
        mostRecentSale: '1.00'
    },
    { 
        set: 'OP01', 
        number: '041', 
        color: 'Verde', 
        name: 'Kouzuki Momonosuke', 
        image_url: 'images/op01/041.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454565/one-piece-card-game-romance-dawn-kouzuki-momonosuke?page=1',
        rarity: 'R',
        cardType: 'Character',
        cost: '1',
        power: '0',
        subtypes: 'Land of Wano Kouzuki Clan',
        attribute: 'Slash',
        artist: '',
        abilities: ['[Activate:Main] (1) (You may rest the specified number of DON!! cards in your cost area) You may rest this Character: Look at 5 cards from the top of your deck; reveal up to 1 "Land of Wano" type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.', 'This card has been officially errata\'d.'],
        marketPrice: '0.24',
        mostRecentSale: '0.15'
    },
    { 
        set: 'OP01', 
        number: '044', 
        color: 'Verde', 
        name: 'Shachi', 
        image_url: 'images/op01/044.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454568/one-piece-card-game-romance-dawn-shachi?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '3',
        power: '4000',
        subtypes: 'Heart Pirates',
        attribute: 'Strike',
        artist: 'Misa Matoki',
        abilities: ['[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)', '[On Play] If you don\'t have [Penguin], play up to 1 [Penguin] from your hand.', 'This card has been officially errata\'d.'],
        marketPrice: '0.07',
        mostRecentSale: '0.08'
    },
    { 
        set: 'OP01', 
        number: '045', 
        color: 'Verde', 
        name: 'Jean Bart', 
        image_url: 'images/op01/045.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454569/one-piece-card-game-romance-dawn-jean-bart?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '4',
        power: '6000',
        subtypes: 'Heart Pirates',
        attribute: 'Strike',
        artist: 'HISASHI HUJIWARA',
        abilities: [],
        marketPrice: '0.08',
        mostRecentSale: '0.05'
    },
    { 
        set: 'OP01', 
        number: '047', 
        color: 'Verde', 
        name: 'Trafalgar Law (047)', 
        image_url: 'images/op01/047.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454571/one-piece-card-game-romance-dawn-trafalgar-law-047?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '5',
        power: '6000',
        subtypes: 'Heart Pirates Supernovas',
        attribute: 'Slash',
        artist: '',
        abilities: ['[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)', '[On Play] You may return 1 Character to your hand: Play up to 1 Character card with a cost of 3 or less from your hand.', 'This card has been officially errata\'d.'],
        marketPrice: '1.01',
        mostRecentSale: '0.99'
    },
    { 
        set: 'OP01', 
        number: '051', 
        color: 'Verde', 
        name: 'Eustass"Captain"Kid', 
        image_url: 'images/op01/051.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454575/one-piece-card-game-romance-dawn-eustasscaptainkid?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '8',
        power: '8000',
        subtypes: 'Kid Pirates Supernovas',
        attribute: 'Special',
        artist: '',
        abilities: ['[DON!! x1] [Opponent\'s Turn] If this Character is rested, your opponent cannot attack any card other than the Character [Eustass"Captain"Kid].', '[Activate:Main] [Once Per Turn] You may rest this Character: Play up to 1 Character card with a cost of 3 or less from your hand.', 'This card has been officially errata\'d.'],
        marketPrice: '1.05',
        mostRecentSale: '0.75'
    },
    { 
        set: 'OP01', 
        number: '053', 
        color: 'Verde', 
        name: 'Wire', 
        image_url: 'images/op01/053.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454578/one-piece-card-game-romance-dawn-wire?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '2',
        power: '4000',
        subtypes: 'Kid Pirates',
        attribute: 'Slash',
        artist: 'Koushi Rokushiro',
        abilities: [],
        marketPrice: '0.10',
        mostRecentSale: '0.04'
    },
    { 
        set: 'OP01', 
        number: '057', 
        color: 'Verde', 
        name: 'Paradise Waterfall', 
        image_url: 'images/op01/057.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454582/one-piece-card-game-romance-dawn-paradise-waterfall?page=1',
        rarity: 'UC',
        cardType: 'Event',
        cost: '1',
        power: '',
        subtypes: 'Land of Wano Kouzuki Clan',
        attribute: '',
        artist: '',
        abilities: ['[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, set up to 1 of your Characters as active.', '[Trigger] K.O. up to 1 of your opponent\'s rested Characters with a cost of 4 or less.', 'This card has been officially errata\'d.'],
        marketPrice: '1.70',
        mostRecentSale: '1.95'
    },
    { 
        set: 'OP01', 
        number: '058', 
        color: 'Verde', 
        name: 'Punk Gibson', 
        image_url: 'images/op01/058.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454583/one-piece-card-game-romance-dawn-punk-gibson?page=1',
        rarity: 'R',
        cardType: 'Event',
        cost: '2',
        power: '',
        subtypes: 'Kid Pirates Supernovas',
        attribute: '',
        artist: '',
        abilities: ['[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, rest up to 1 of your opponent\'s Characters with a cost of 4 or less.', '[Trigger] Rest up to 1 of your opponent\'s Characters.', 'This card has been officially errata\'d.'],
        marketPrice: '0.67',
        mostRecentSale: '0.72'
    },
    { 
        set: 'OP01', 
        number: '070', 
        color: 'Azul', 
        name: 'Dracule Mihawk', 
        image_url: 'images/op01/070.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454598/one-piece-card-game-romance-dawn-dracule-mihawk?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '9',
        power: '9000',
        subtypes: 'The Seven Warlords of the Sea',
        attribute: 'Slash',
        artist: 'Nijihayashi',
        abilities: ['[On Play] Place up to 1 Character with a cost of 7 or less at the bottom of the owner\'s deck.', 'This card has been officially errata\'d.'],
        marketPrice: '1.13',
        mostRecentSale: '1.39'
    },
    { 
        set: 'OP01', 
        number: '074', 
        color: 'Azul', 
        name: 'Bartholomew Kuma', 
        image_url: 'images/op01/074.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454604/one-piece-card-game-romance-dawn-bartholomew-kuma?page=1',
        rarity: 'R',
        cardType: 'Character',
        cost: '4',
        power: '5000',
        subtypes: 'Revolutionary Army The Seven Warlords of the Sea',
        attribute: 'Strike',
        artist: 'Moopic',
        abilities: ['[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)', '[On K.O.] Play up to 1 [Pacifista] with a cost of 4 or less from your hand.', 'This card has been officially errata\'d.'],
        marketPrice: '0.24',
        mostRecentSale: '0.19'
    },
    { 
        set: 'OP01', 
        number: '077', 
        color: 'Azul', 
        name: 'Perona', 
        image_url: 'images/op01/077.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454607/one-piece-card-game-romance-dawn-perona?page=1',
        rarity: 'UC',
        cardType: 'Character',
        cost: '1',
        power: '2000',
        subtypes: 'Thriller Bark Pirates',
        attribute: 'Special',
        artist: 'Ryuda',
        abilities: ['[On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of the deck in any order.'],
        marketPrice: '0.71',
        mostRecentSale: '0.48'
    },
    { 
        set: 'OP01', 
        number: '078', 
        color: 'Azul', 
        name: 'Boa Hancock', 
        image_url: 'images/op01/078.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454608/one-piece-card-game-romance-dawn-boa-hancock?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '4',
        power: '5000',
        subtypes: 'Kuja Pirates The Seven Warlords of the Sea',
        attribute: 'Special',
        artist: 'Mutsumi Sasaki',
        abilities: ['[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)', '[DON!! x1] [When Attacking]/[On Block] Draw 1 card if you have 5 or less cards in your hand.'],
        marketPrice: '0.72',
        mostRecentSale: '0.50'
    },
    { 
        set: 'OP01', 
        number: '093', 
        color: 'Morado', 
        name: 'Ulti', 
        image_url: 'images/op01/093.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454625/one-piece-card-game-romance-dawn-ulti?page=1',
        rarity: 'R',
        cardType: 'Character',
        cost: '2',
        power: '3000',
        subtypes: 'Animal Kingdom Pirates',
        attribute: 'Strike',
        artist: 'Hagane Tsurugi',
        abilities: ['[On Play] (1) (You may rest the specified number of DON!! cards in your cost area.): Add up to 1 DON!! card from your DON!! deck and rest it.', 'This card has been officially errata\'d.'],
        marketPrice: '0.19',
        mostRecentSale: '0.10'
    },
    { 
        set: 'OP01', 
        number: '094', 
        color: 'Morado', 
        name: 'Kaido (094)', 
        image_url: 'images/op01/094.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/453521/one-piece-card-game-romance-dawn-kaido-094?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '10',
        power: '12000',
        subtypes: 'Animal Kingdom Pirates The Four Emperors',
        attribute: 'Strike',
        artist: 'Yosuke Adachi',
        abilities: ['[On Play] DON!! -6 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the "Animal Kingdom Pirates" type, K.O. all Characters other than this Character.'],
        marketPrice: '0.95',
        mostRecentSale: '0.99'
    },
    { 
        set: 'OP01', 
        number: '096', 
        color: 'Morado', 
        name: 'King (096)', 
        image_url: 'images/op01/096.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454629/one-piece-card-game-romance-dawn-king-096?page=1',
        rarity: 'SR',
        cardType: 'Character',
        cost: '7',
        power: '7000',
        subtypes: 'Animal Kingdom Pirates',
        attribute: 'Special',
        artist: 'DAI•XT',
        abilities: ['[On Play] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent\'s Characters with a cost of 3 or less and up to 1 of your opponent\'s Characters with a cost of 2 or less.', 'This card has been officially errata\'d.'],
        marketPrice: '0.57',
        mostRecentSale: '0.59'
    },
    { 
        set: 'OP01', 
        number: '097', 
        color: 'Morado', 
        name: 'Queen', 
        image_url: 'images/op01/097.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454631/one-piece-card-game-romance-dawn-queen?page=1',
        rarity: 'R',
        cardType: 'Character',
        cost: '6',
        power: '5000',
        subtypes: 'Animal Kingdom Pirates',
        attribute: 'Strike',
        artist: 'Misa Tsutsui',
        abilities: ['[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains [Rush] during this turn. Then, give up to 1 of your opponent\'s Characters -2000 power during this turn. (This card can attack on the turn in which it is played.)', 'This card has been officially errata\'d.'],
        marketPrice: '0.14',
        mostRecentSale: '0.12'
    },
    { 
        set: 'OP01', 
        number: '106', 
        color: 'Morado', 
        name: 'Basil Hawkins', 
        image_url: 'images/op01/106.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454642/one-piece-card-game-romance-dawn-basil-hawkins?page=1',
        rarity: 'UC',
        cardType: 'Character',
        cost: '4',
        power: '2000',
        subtypes: 'Animal Kingdom Pirates Hawkins Pirates',
        attribute: 'Slash',
        artist: 'Hatori Kyoka',
        abilities: ['[On Play] Add up to 1 DON!! card from your DON!! deck and rest it.', '[Trigger] Play this card.', 'This card has been officially errata\'d.'],
        marketPrice: '0.22',
        mostRecentSale: '0.25'
    },
    { 
        set: 'OP01', 
        number: '107', 
        color: 'Morado', 
        name: 'Babanuki', 
        image_url: 'images/op01/107.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454643/one-piece-card-game-romance-dawn-babanuki?page=1',
        rarity: 'C',
        cardType: 'Character',
        cost: '5',
        power: '7000',
        subtypes: 'Animal Kingdom Pirates SMILE',
        attribute: 'Ranged',
        artist: 'HISASHI HUJIWARA',
        abilities: [],
        marketPrice: '0.06',
        mostRecentSale: '0.04'
    },
    { 
        set: 'OP01', 
        number: '111', 
        color: 'Morado', 
        name: 'Black Maria', 
        image_url: 'images/op01/111.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454646/one-piece-card-game-romance-dawn-black-maria?page=1',
        rarity: 'R',
        cardType: 'Character',
        cost: '4',
        power: '5000',
        subtypes: 'Animal Kingdom Pirates',
        attribute: 'Special',
        artist: 'Mutsumi Sasaki',
        abilities: ['[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)', '[On Block] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains +1000 power during this turn.'],
        marketPrice: '0.14',
        mostRecentSale: '0.11'
    },
    { 
        set: 'OP01', 
        number: '119', 
        color: 'Morado', 
        name: 'Thunder Bagua', 
        image_url: 'images/op01/119.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454663/one-piece-card-game-romance-dawn-thunder-bagua?page=1',
        rarity: 'R',
        cardType: 'Event',
        cost: '2',
        power: '',
        subtypes: 'Animal Kingdom Pirates The Four Emperors',
        attribute: '',
        artist: '',
        abilities: ['[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 2 or less Life cards, add up to 1 DON!! card from your DON!! deck and rest it.', '[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.', 'This card has been officially errata\'d.'],
        marketPrice: '3.87',
        mostRecentSale: '4.99'
    },
    { 
        set: 'OP01', 
        number: '120', 
        color: 'Rojo', 
        name: 'Shanks', 
        image_url: 'images/op01/120.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454664/one-piece-card-game-romance-dawn-shanks?page=1',
        rarity: 'SEC',
        cardType: 'Character',
        cost: '9',
        power: '10000',
        subtypes: 'The Four Emperors Red-Haired Pirates',
        attribute: 'Slash',
        artist: 'Makitoshi',
        abilities: ['[Rush] (This card can attack on the turn in which it is played.)', '[When Attacking] Your opponent cannot activate a [Blocker] Character that has 2000 or less power during this battle.'],
        marketPrice: '3.84',
        mostRecentSale: '2.50'
    },
    { 
        set: 'OP01', 
        number: '121', 
        color: 'Verde', 
        name: 'Yamato', 
        image_url: 'images/op01/121.png', 
        tcgplayer_url: 'https://www.tcgplayer.com/product/454667/one-piece-card-game-romance-dawn-yamato?page=1',
        rarity: 'SEC',
        cardType: 'Character',
        cost: '5',
        power: '5000',
        subtypes: 'Land of Wano',
        attribute: 'Strike',
        artist: '',
        abilities: [],
        marketPrice: '',
        mostRecentSale: '6.05'
    }
];
